// USAGE - define PROCESS_OGL_FUNCTION, include this file.

#ifndef PROCESS_GL_FUNC
#error
#endif

// Multitexturing
PROCESS_GL_FUNC( PFNGLACTIVETEXTUREPROC, glActiveTexture );
PROCESS_GL_FUNC( PFNGLMULTITEXCOORD2FPROC, glMultiTexCoord2f );

// Shaders
PROCESS_GL_FUNC( PFNGLCREATESHADERPROC, glCreateShader );
PROCESS_GL_FUNC( PFNGLDELETESHADERPROC, glDeleteShader );
PROCESS_GL_FUNC( PFNGLSHADERSOURCEPROC, glShaderSource );
PROCESS_GL_FUNC( PFNGLCOMPILESHADERPROC, glCompileShader );
PROCESS_GL_FUNC( PFNGLGETSHADERIVPROC, glGetShaderiv );
PROCESS_GL_FUNC( PFNGLGETSHADERINFOLOGPROC, glGetShaderInfoLog );

// programs
PROCESS_GL_FUNC( PFNGLCREATEPROGRAMPROC, glCreateProgram );
PROCESS_GL_FUNC( PFNGLDELETEPROGRAMPROC, glDeleteProgram );
PROCESS_GL_FUNC( PFNGLDETACHSHADERPROC, glDetachShader );
PROCESS_GL_FUNC( PFNGLATTACHSHADERPROC, glAttachShader );
PROCESS_GL_FUNC( PFNGLLINKPROGRAMPROC, glLinkProgram );
PROCESS_GL_FUNC( PFNGLUSEPROGRAMPROC, glUseProgram );
PROCESS_GL_FUNC( PFNGLGETPROGRAMIVPROC, glGetProgramiv );
PROCESS_GL_FUNC( PFNGLGETPROGRAMINFOLOGPROC, glGetProgramInfoLog );
PROCESS_GL_FUNC( PFNGLGETATTRIBLOCATIONPROC, glGetAttribLocation );

//uniforms
PROCESS_GL_FUNC( PFNGLGETUNIFORMLOCATIONPROC, glGetUniformLocation );
PROCESS_GL_FUNC( PFNGLGETACTIVEUNIFORMPROC, glGetActiveUniform );
PROCESS_GL_FUNC( PFNGLUNIFORMMATRIX4FVPROC, glUniformMatrix4fv );
PROCESS_GL_FUNC( PFNGLUNIFORMMATRIX3FVPROC, glUniformMatrix3fv );
PROCESS_GL_FUNC( PFNGLUNIFORM1IPROC, glUniform1i );
PROCESS_GL_FUNC( PFNGLUNIFORM1FPROC, glUniform1f );
PROCESS_GL_FUNC( PFNGLUNIFORM2FPROC, glUniform2f );
PROCESS_GL_FUNC( PFNGLUNIFORM3FPROC, glUniform3f );
PROCESS_GL_FUNC( PFNGLUNIFORM4FPROC, glUniform4f );